# Dubbo config properties
dubbo:
  application:
    name: dubbo-consumer-demo
    id: dubbo-consumer-demo
  protocol:
    name: dubbo
    port: 12346
  registry:
    id: consumer
    address: zookeeper://127.0.0.1:2181
