spring:
  application:
    name: dubbo-demo
  profiles:
    active:
      dev
  jackson:
    time-zone: GMT+8
    
server:
  port: 8080
  servlet:
    context-path: /
    
# Dubbo config properties
dubbo:
  application:
    name: dubbo-demo
    id: dubbo-demo
  protocol:
    name: dubbo
    port: 3864
  registry:
    id: my-registry
    address: zookeeper://127.0.0.1:2181
