# Dubbo config properties
dubbo:
  application:
    name: dubbo-demo
    id: dubbo-demo
  protocol:
    name: dubbo
    port: 3864
  registry:
    id: provider
    address: zookeeper://127.0.0.1:2181
